### ISSUE TITLE
ADServiceAccount: Add support for Group Managed Service Accounts on target machine

### ISSUE THREAD

**Issue by jlongo62** [dsccommunity/ComputerManagementDsc#236]
ISSUE TITLE:
ADServiceAccount: Add support for Group Managed Service Accounts on target machine

    ISSUE DESCRIPTION:

There does not appear to be support for Group Managed Service Accounts via DSC implemented via [Install-ADServiceAccount](https://docs.microsoft.com/en-us/powershell/module/addsadministration/install-adserviceaccount?view=win10-ps)

Suggest DSC modules adding:
Install-ADServiceAccount -Identity 'xxx'
Test-AdServiceAccount -Identity 'xxx'

**Comment by PlagueHO** [comment]
Hi @jlongo62 - thanks for raising this. It does look like a gap - I also checked in ActiveDirectoryDsc and it does not look like it is in there either, although there is the ability to create MSA/gMSA in there.

The question I'd have is: is the resource most appropriate in this module or within the ActiveDirectoryDsc module? @johlju - any thoughts on this one?

**Comment by johlju** [comment]
This is being discussed here https://github.com/PowerShell/ActiveDirectoryDsc/issues/265 

Since the cmdlets requires having the ADDSAdministration module installed, if the resource would be here it will be a prerequisites for this particular resource. The resources in ActiveDirectoryDsc already have this prerequisites.  Although, as @PlagueHO says in previous comment, that resource would target more computers than just domain controllers. But so could ADUser and ADGroup, etc. They don't need to be run on a domain controller to add users and groups, although they update the domain (controllers) which this resource would not do, it would only target the computer it is run on.

My though is to keep ComputerMangementDsc to have resources that can be used without needing prerequisites other than is already installed in the OS by default. 🤔  Then this resource would fit better in ActiveDirectoryDsc.

But if t would be added here, then I would be okay with that too.

**Comment by PlagueHO** [comment]
@johlju - really great point about the dependence on ADDSAdmin module. I think it would be best to avoid adding a dependency on ADDSAdmin in this module. So I agree- I think the resource is better suited to ActiveDirectoryDsc.

**Comment by johlju** [comment]
@jlongo62 Please see issue https://github.com/PowerShell/ActiveDirectoryDsc/issues/265 and see if you can contribute to the discussion, or even better send in a PR to ActiveDirectoryDsc to help resolve this.

Suggest to close this issue as this time since we are tracking this in https://github.com/PowerShell/ActiveDirectoryDsc/issues/265.

**Comment by johlju** [comment]
Closing this issue and we continue to track it in https://github.com/dsccommunity/ActiveDirectoryDsc/issues/265.
